import { Injectable, signal, effect, computed } from '@angular/core';

export type Language = 'en' | 'ru' | 'de' | 'es' | 'uk';

export const languages: { code: Language, name: string }[] = [
    { code: 'en', name: 'EN' },
    { code: 'de', name: 'DE' },
    { code: 'es', name: 'ES' },
    { code: 'uk', name: 'UA' },
    { code: 'ru', name: 'RU' },
];

const LOCAL_STORAGE_KEY_LANGUAGE = 'workout-timer-language';

const dictionaries: Record<Language, any> = {
  en: {
    mute: 'Mute',
    unmute: 'Unmute',
    baseWorkout: 'Base Workout',
    advancedWorkout: 'Advanced Workout',
    restDuration: 'Rest Duration',
    exerciseDurationMultiplier: 'Exercise Duration Multiplier',
    fullWorkoutRoutine: 'Full Workout Routine',
    startWorkout: 'Start Workout',
    startOver: 'Start Over',
    totalTimeLeft: 'Total Time Left:',
    movement: 'Movement:',
    exerciseAnimation: 'Exercise animation',
    next: 'Next:',
    finalRoundComplete: 'Final Round Complete!',
    coolDown: 'Time to cool down and stretch.',
    goBack: 'Go Back',
    skipRest: 'Skip Rest',
    skipExercise: 'Skip Exercise',
    pause: 'Pause',
    pauseRest: 'Pause Rest',
    resume: 'RESUME',
    paused: 'PAUSED',
    total: 'Total:',
    exercise: 'Exercise',
    of: 'of',
    rest: 'REST',
    round: 'Round',
    complete: 'Complete',
    workoutTitle: 'Workout',
    clickStart: "Adjust settings below, then press Start when you're ready.",
    workoutComplete: 'Workout Complete!',
    workoutCompleteMessage: 'Great Job! You have completed your workout.',
    updateAvailable: 'A new version is available!',
    applyUpdate: 'Update Now',
    installApp: 'Install App',
    exercises: {
      catCow_name: "Cat Cow",
      catCow_explanation: "Start on all fours. Inhale as you drop your belly and look up (Cow). Exhale as you round your spine and tuck your chin (Cat).",
      birdDogLeft_name: "Bird Dog (Left)",
      birdDogLeft_explanation: "Start on all fours. Extend left arm forward and right leg backward. Hold.",
      birdDogRight_name: "Bird Dog (Right)",
      birdDogRight_explanation: "Start on all fours. Extend right arm forward and left leg backward. Hold.",
      pushUps_name: "Push-Ups",
      pushUps_explanation: "Start in a high plank. Lower your body until your chest nearly touches the floor, keeping your body straight. Push back up.",
      singleLegGluteBridgeLeft_name: "Single Leg Glute Bridge (Left)",
      singleLegGluteBridgeLeft_explanation: "Lie on your back, knees bent, feet flat. Extend right leg straight. Lift hips using your left glute until your body forms a straight line. Squeeze, then lower.",
      singleLegGluteBridgeRight_name: "Single Leg Glute Bridge (Right)",
      singleLegGluteBridgeRight_explanation: "Lie on your back, knees bent, feet flat. Extend left leg straight. Lift hips using your right glute until your body forms a straight line. Squeeze, then lower.",
      sidePlankRight_name: "Side Plank (Right)",
      sidePlankRight_explanation: "Lie on right side, support weight on right forearm, lift hips until the body forms a straight line.",
      sidePlankLeft_name: "Side Plank (Left)",
      sidePlankLeft_explanation: "Lie on left side, support weight on left forearm, lift hips until the body forms a straight line.",
      plank_name: "Plank",
      plank_explanation: "Hold the push-up position on forearms, maintaining a straight line from head to heels.",
      cossackSquats_name: "Cossack Squats",
      cossackSquats_explanation: "Stand with feet wider than shoulder-width. Shift your weight to one side, bending that knee while keeping the other leg straight. Keep your chest up. Return to start and repeat on the other side.",
      quadStretchLeft_name: "Quad Stretch (Left)",
      quadStretchLeft_explanation: "Stand on your right leg, bend your left knee, and grab your left ankle. Pull it gently towards your glutes. Keep your knees together.",
      quadStretchRight_name: "Quad Stretch (Right)",
      quadStretchRight_explanation: "Stand on your left leg, bend your right knee, and grab your right ankle. Pull it gently towards your glutes. Keep your knees together.",
      wallCalfStretchLeft_name: "Wall Calf Stretch (Left)",
      wallCalfStretchLeft_explanation: "Stand facing a wall. Place your hands on the wall for support. Step your left foot back, keeping your left leg straight and heel on the floor. Lean into the wall until you feel a stretch in your left calf.",
      wallCalfStretchRight_name: "Wall Calf Stretch (Right)",
      wallCalfStretchRight_explanation: "Stand facing a wall. Place your hands on the wall for support. Step your right foot back, keeping your right leg straight and heel on the floor. Lean into the wall until you feel a stretch in your right calf.",
      eccentricCalfRaiseLeft_name: "Eccentric Calf Raise (Left)",
      eccentricCalfRaiseLeft_explanation: "Stand on a step or block on your left foot. Rise up on the ball of your foot, then slowly lower your heel below the level of the step.",
      eccentricCalfRaiseRight_name: "Eccentric Calf Raise (Right)",
      eccentricCalfRaiseRight_explanation: "Stand on a step or block on your right foot. Rise up on the ball of your foot, then slowly lower your heel below the level of the step.",
      shortFootLeft_name: "Short Foot (Left)",
      shortFootLeft_explanation: "Sit or stand barefoot. Keep your left heel and the base of your toes on the floor. Pull the ball of your left foot towards your heel, arching your midfoot. Hold, then relax.",
      shortFootRight_name: "Short Foot (Right)",
      shortFootRight_explanation: "Sit or stand barefoot. Keep your right heel and the base of your toes on the floor. Pull the ball of your right foot towards your heel, arching your midfoot. Hold, then relax.",
      ywRaises_name: "Y-W Raises (Standing)",
      ywRaises_explanation: "Stand tall. Raise your arms up to form a 'Y' shape, squeezing the shoulders. Lower them, then squeeze shoulder blades together pulling elbows down to form a 'W'. Repeat.",
      activeHang_name: "Active Hang",
      activeHang_explanation: "Hang from a pull-up bar. Engage your lats and shoulders by pulling your shoulder blades down and back, lifting your chest slightly. Hold.",
      childPose_name: "Child's Pose",
      childPose_explanation: "Kneel on the floor, sit on your heels, and lean forward, stretching your arms in front of you on the floor.",
      negativePullups_name: "Negative Pull-ups",
      negativePullups_explanation: "Jump or use a box to get your chin over the bar. Slowly and with control, lower yourself down until your arms are fully extended. Repeat.",
      legSwingsLeft_name: "Leg Swings (Left)",
      legSwingsLeft_explanation: "Stand tall, hold onto a wall for balance. Swing your left leg forward and backward, keeping your core engaged.",
      legSwingsRight_name: "Leg Swings (Right)",
      legSwingsRight_explanation: "Stand tall, hold onto a wall for balance. Swing your right leg forward and backward, keeping your core engaged.",
      jumpingJacks_name: "Jumping Jacks",
      jumpingJacks_explanation: "Start standing with legs together and arms at your sides. Jump up, spread your legs, and bring both hands together above your head. Return to start.",
      armCircles_name: "Arm Circles",
      armCircles_explanation: "Stand with feet shoulder-width apart and extend arms parallel to the floor. Make small circular motions with both arms, then reverse direction halfway.",
      gluteBridgeDynamic_name: "Dynamic Glute Bridge",
      gluteBridgeDynamic_explanation: "Lie on your back with knees bent and feet flat. Squeeze glutes and push your hips up toward the ceiling. Lower back down and repeat.",
      plankToeTouches_name: "Plank Toe Touches",
      plankToeTouches_explanation: "Start in a high plank position. Push your hips up into a downward dog while reaching your right hand to your left toe. Return to plank and alternate sides.",
      threadNeedleLeft_name: "Thread the Needle (Left)",
      threadNeedleLeft_explanation: "On all fours, slide your left arm under your right to open up the shoulder blade.",
      threadNeedleRight_name: "Thread the Needle (Right)",
      threadNeedleRight_explanation: "On all fours, slide your right arm under your left to open up the shoulder blade.",
      deadBug_name: "Dead Bug",
      deadBug_explanation: "Slow and controlled! Press your lower back firmly into the floor.",
      reverseLungeLLegLead_name: "Reverse Lunge (L leg lead)",
      reverseLungeLLegLead_explanation: "Step back with the right leg. Keep your torso strictly vertical.",
      reverseLungeRLegLead_name: "Reverse Lunge (R leg lead)",
      reverseLungeRLegLead_explanation: "Step back with the left leg. Keep your torso strictly vertical.",
      standingRollDown_name: "Standing Roll-Down",
      standingRollDown_explanation: "Roll down vertebra by vertebra toward your toes, then slowly back up.",
    }
  },
  ru: {
    mute: 'Выкл. звук',
    unmute: 'Вкл. звук',
    baseWorkout: 'Базовая тренировка',
    advancedWorkout: 'Продвинутая тренировка',
    restDuration: 'Продолжительность отдыха',
    exerciseDurationMultiplier: 'Множитель длительности',
    fullWorkoutRoutine: 'Программа тренировки',
    startWorkout: 'Начать тренировку',
    startOver: 'Начать заново',
    totalTimeLeft: 'Всего осталось:',
    movement: 'Движение:',
    exerciseAnimation: 'Анимация упражнения',
    next: 'Далее:',
    finalRoundComplete: 'Последний раунд завершен!',
    coolDown: 'Время для заминки и растяжки.',
    goBack: 'Назад',
    skipRest: 'Пропустить отдых',
    skipExercise: 'Пропустить упражнение',
    pause: 'Пауза',
    pauseRest: 'Пауза (отдых)',
    resume: 'ПРОДОЛЖИТЬ',
    paused: 'ПАУЗА',
    total: 'Продожительность:',
    exercise: 'Упражнение',
    of: 'из',
    rest: 'ОТДЫХ',
    round: 'Раунд',
    complete: 'Выполнено',
    workoutTitle: 'Тренировка',
    clickStart: 'Настройте параметры ниже, затем нажмите Старт, когда будете готовы.',
    workoutComplete: 'Тренировка завершена!',
    workoutCompleteMessage: 'Отличная работа! Тренировка завершена.',
    updateAvailable: 'Доступна новая версия!',
    applyUpdate: 'Обновить сейчас',
    installApp: 'Установить приложение',
    exercises: {
      catCow_name: "Кошка-Корова",
      catCow_explanation: "Начните на четвереньках. Вдохните, прогибая спину и поднимая голову (Корова). Выдохните, округляя спину и прижимая подбородок к груди (Кошка).",
      birdDogLeft_name: "Птица-Собака (левая)",
      birdDogLeft_explanation: "Начните на четвереньках. Вытяните левую руку вперед и правую ногу назад. Удерживайте.",
      birdDogRight_name: "Птица-Собака (правая)",
      birdDogRight_explanation: "Начните на четвереньках. Вытяните правую руку вперед и левую ногу назад. Удерживайте.",
      pushUps_name: "Отжимания",
      pushUps_explanation: "Начните в высокой планке. Опускайте тело, пока грудь почти не коснется пола, держа тело прямо. Вернитесь в исходное положение.",
      singleLegGluteBridgeLeft_name: "Ягодичный мостик на одной ноге (левая)",
      singleLegGluteBridgeLeft_explanation: "Лягте на спину, колени согнуты. Выпрямите правую ногу. Поднимайте бедра за счет левой ягодицы, пока тело не образует прямую линию. Сожмите ягодицу, затем опуститесь.",
      singleLegGluteBridgeRight_name: "Ягодичный мостик на одной ноге (правая)",
      singleLegGluteBridgeRight_explanation: "Лягте на спину, колени согнуты. Выпрямите левую ногу. Поднимайте бедра за счет правой ягодицы, пока тело не образует прямую линию. Сожмите ягодицу, затем опуститесь.",
      sidePlankRight_name: "Боковая планка (правая)",
      sidePlankRight_explanation: "Лягте на правый бок, опираясь на правое предплечье, поднимите бедра, пока тело не образует прямую линию.",
      sidePlankLeft_name: "Боковая планка (левая)",
      sidePlankLeft_explanation: "Лягте на левый бок, опираясь на левое предплечье, поднимите бедра, пока тело не образует прямую линию.",
      plank_name: "Планка",
      plank_explanation: "Удерживайте положение отжимания на предплечьях, сохраняя прямую линию от головы до пяток.",
      cossackSquats_name: "Казачьи приседания",
      cossackSquats_explanation: "Встаньте, ноги шире плеч. Перенесите вес на одну сторону, согнув это колено, оставляя другую ногу прямой. Держите грудь прямо. Вернитесь в исходное положение и повторите в другую сторону.",
      quadStretchLeft_name: "Растяжка квадрицепса (левая)",
      quadStretchLeft_explanation: "Встаньте на правую ногу, согните левое колено и возьмитесь за левую лодыжку. Мягко потяните ее к ягодицам. Держите колени вместе.",
      quadStretchRight_name: "Растяжка квадрицепса (правая)",
      quadStretchRight_explanation: "Встаньте на левую ногу, согните правое колено и возьмитесь за правую лодыжку. Мягко потяните ее к ягодицам. Держите колени вместе.",
      wallCalfStretchLeft_name: "Растяжка икр у стены (левая)",
      wallCalfStretchLeft_explanation: "Встаньте лицом к стене. Обопритесь руками о стену. Отшагните левой ногой назад, держа левую ногу прямой, а пятку на полу. Наклонитесь к стене, пока не почувствуете растяжение в левой икре.",
      wallCalfStretchRight_name: "Растяжка икр у стены (правая)",
      wallCalfStretchRight_explanation: "Встаньте лицом к стене. Обопритесь руками о стену. Отшагните правой ногой назад, держа правую ногу прямой, а пятку на полу. Наклонитесь к стене, пока не почувствуете растяжение в правой икре.",
      eccentricCalfRaiseLeft_name: "Эксцентрический подъем на носок (левая)",
      eccentricCalfRaiseLeft_explanation: "Встаньте на ступеньку на левую ногу. Поднявшись на носок, медленно опустите пятку ниже уровня ступеньки.",
      eccentricCalfRaiseRight_name: "Эксцентрический подъем на носок (правая)",
      eccentricCalfRaiseRight_explanation: "Встаньте на ступеньку на правую ногу. Поднявшись на носок, медленно опустите пятку ниже уровня ступеньки.",
      shortFootLeft_name: "Короткая стопа (левая)",
      shortFootLeft_explanation: "Сядьте или встаньте босиком. Держите левую пятку и основание пальцев ног на полу. Потяните подушечку левой стопы к пятке, приподнимая свод стопы. Удерживайте, затем расслабьте.",
      shortFootRight_name: "Короткая стопа (правая)",
      shortFootRight_explanation: "Сядьте или встаньте босиком. Держите правую пятку и основание пальцев ног на полу. Потяните подушечку правой стопы к пятке, приподнимая свод стопы. Удерживайте, затем расслабьте.",
      ywRaises_name: "Y-W подъемы (стоя)",
      ywRaises_explanation: "Встаньте прямо. Поднимите руки вверх, образуя форму 'Y', сводя лопатки. Опустите их, затем сведите лопатки вместе, опуская локти вниз, образуя форму 'W'. Повторите.",
      activeHang_name: "Активный вис на турнике",
      activeHang_explanation: "Повисните на турнике. Напрягите широчайшие мышцы и плечи, опустив лопатки вниз и назад, слегка приподняв грудь. Удерживайте положение.",
      childPose_name: "Поза ребенка",
      childPose_explanation: "Встаньте на колени, сядьте на пятки и наклонитесь вперед, вытянув руки перед собой на полу.",
      negativePullups_name: "Негативные подтягивания",
      negativePullups_explanation: "Подпрыгните или используйте подставку, чтобы подбородок оказался над перекладиной. Медленно и под контролем опускайтесь, пока руки полностью не выпрямятся. Повторите.",
      legSwingsLeft_name: "Махи ногой (левая)",
      legSwingsLeft_explanation: "Встаньте прямо, держитесь за стену для равновесия. Делайте махи левой ногой вперед и назад, напрягая мышцы кора.",
      legSwingsRight_name: "Махи ногой (правая)",
      legSwingsRight_explanation: "Встаньте прямо, держитесь за стену для равновесия. Делайте махи правой ногой вперед и назад, напрягая мышцы кора.",
      jumpingJacks_name: "Джампинг Джек (Прыжки с разведением рук и ног)",
      jumpingJacks_explanation: "Встаньте прямо, ноги вместе, руки по швам. Подпрыгните, разведите ноги в стороны и хлопните в ладоши над головой. Вернитесь в исходное.",
      armCircles_name: "Круговые вращения руками",
      armCircles_explanation: "Встаньте, ноги на ширине плеч, вытяните руки параллельно полу. Делайте небольшие круговые движения руками, затем поменяйте направление.",
      gluteBridgeDynamic_name: "Динамичный ягодичный мостик",
      gluteBridgeDynamic_explanation: "Лягте на спину, согните колени. Напрягите ягодицы и поднимите таз вверх. Затем опуститесь обратно и повторите.",
      plankToeTouches_name: "Планка с касанием стопы",
      plankToeTouches_explanation: "Начните в положении высокой планки. Поднимите таз вверх, касаясь правой рукой левой стопы. Вернитесь в планку и поменяйте сторону.",
      threadNeedleLeft_name: "Игольное ушко (левая)",
      threadNeedleLeft_explanation: "На четвереньках просуньте левую руку под правую, чтобы раскрыть лопатку.",
      threadNeedleRight_name: "Игольное ушко (правая)",
      threadNeedleRight_explanation: "На четвереньках просуньте правую руку под левую, чтобы раскрыть лопатку.",
      deadBug_name: "Мертвый жук",
      deadBug_explanation: "Медленно и под контролем! Плотно прижмите поясницу к полу.",
      reverseLungeLLegLead_name: "Обратный выпад (левая нога впереди)",
      reverseLungeLLegLead_explanation: "Сделайте шаг назад правой ногой. Держите туловище строго вертикально.",
      reverseLungeRLegLead_name: "Обратный выпад (правая нога впереди)",
      reverseLungeRLegLead_explanation: "Сделайте шаг назад левой ногой. Держите туловище строго вертикально.",
      standingRollDown_name: "Раскручивание стоя",
      standingRollDown_explanation: "Наклоняйтесь вниз позвонок за позвонком к пальцам ног, а затем медленно возвращайтесь обратно.",
    }
  },
  de: {
    mute: 'Stumm',
    unmute: 'Ton an',
    baseWorkout: 'Basistraining',
    advancedWorkout: 'Fortgeschrittenes Training',
    restDuration: 'Pausendauer',
    exerciseDurationMultiplier: 'Übungsdauer-Multiplikator',
    fullWorkoutRoutine: 'Komplettes Trainingsprogramm',
    startWorkout: 'Training starten',
    startOver: 'Neu starten',
    totalTimeLeft: 'Verbleibende Gesamtzeit:',
    movement: 'Bewegung:',
    exerciseAnimation: 'Übungsanimation',
    next: 'Nächste:',
    finalRoundComplete: 'Letzte Runde abgeschlossen!',
    coolDown: 'Zeit zum Abkühlen und Dehnen.',
    goBack: 'Zurück',
    skipRest: 'Pause überspringen',
    skipExercise: 'Übung überspringen',
    pause: 'Pause',
    pauseRest: 'Pause (Erholung)',
    resume: 'FORTSETZEN',
    paused: 'PAUSIERT',
    total: 'Gesamt:',
    exercise: 'Übung',
    of: 'von',
    rest: 'PAUSE',
    round: 'Runde',
    complete: 'Abgeschlossen',
    workoutTitle: 'Training',
    clickStart: 'Passen Sie die Einstellungen unten an und drücken Sie dann Start, wenn Sie bereit sind.',
    workoutComplete: 'Training abgeschlossen!',
    workoutCompleteMessage: 'Gut gemacht! Du hast dein Training abgeschlossen.',
    updateAvailable: 'Eine neue Version ist verfügbar!',
    applyUpdate: 'Jetzt aktualisieren',
    installApp: 'App installieren',
    exercises: {
      catCow_name: "Katze-Kuh",
      catCow_explanation: "Beginnen Sie im Vierfüßlerstand. Atmen Sie ein, während Sie den Bauch senken und nach oben schauen (Kuh). Atmen Sie aus, während Sie den Rücken runden und das Kinn zur Brust ziehen (Katze).",
      birdDogLeft_name: "Vogel-Hund (Links)",
      birdDogLeft_explanation: "Beginnen Sie im Vierfüßlerstand. Strecken Sie den linken Arm nach vorne und das rechte Bein nach hinten. Halten.",
      birdDogRight_name: "Vogel-Hund (Rechts)",
      birdDogRight_explanation: "Beginnen Sie im Vierfüßlerstand. Strecken Sie den rechten Arm nach vorne und das linke Bein nach hinten. Halten.",
      pushUps_name: "Liegestütze",
      pushUps_explanation: "Beginnen Sie in einer hohen Planke. Senken Sie Ihren Körper ab, bis Ihre Brust fast den Boden berührt, halten Sie Ihren Körper gerade. Drücken Sie sich wieder nach oben.",
      singleLegGluteBridgeLeft_name: "Einbeinige Gesäßbrücke (Links)",
      singleLegGluteBridgeLeft_explanation: "Legen Sie sich auf den Rücken, Knie gebeugt. Strecken Sie das rechte Bein aus. Heben Sie die Hüften mit dem linken Gesäßmuskel an, bis der Körper eine gerade Linie bildet. Anspannen, dann senken.",
      singleLegGluteBridgeRight_name: "Einbeinige Gesäßbrücke (Rechts)",
      singleLegGluteBridgeRight_explanation: "Legen Sie sich auf den Rücken, Knie gebeugt. Strecken Sie das linke Bein aus. Heben Sie die Hüften mit dem rechten Gesäßmuskel an, bis der Körper eine gerade Linie bildet. Anspannen, dann senken.",
      sidePlankRight_name: "Seitstütz (Rechts)",
      sidePlankRight_explanation: "Legen Sie sich auf die rechte Seite, stützen Sie das Gewicht auf dem rechten Unterarm ab, heben Sie die Hüften, bis der Körper eine gerade Linie bildet.",
      sidePlankLeft_name: "Seitstütz (Links)",
      sidePlankLeft_explanation: "Legen Sie sich auf die linke Seite, stützen Sie das Gewicht auf dem linken Unterarm ab, heben Sie die Hüften, bis der Körper eine gerade Linie bildet.",
      plank_name: "Planke",
      plank_explanation: "Halten Sie die Liegestützposition auf den Unterarmen und achten Sie auf eine gerade Linie von Kopf bis Fersen.",
      cossackSquats_name: "Kosaken-Kniebeugen",
      cossackSquats_explanation: "Stehen Sie mit den Füßen weiter als schulterbreit auseinander. Verlagern Sie Ihr Gewicht auf eine Seite, beugen Sie dieses Knie, während Sie das andere Bein gerade halten. Halten Sie die Brust aufrecht. Kehren Sie zur Ausgangsposition zurück und wiederholen Sie auf der anderen Seite.",
      quadStretchLeft_name: "Quadrizeps-Dehnung (Links)",
      quadStretchLeft_explanation: "Stehen Sie auf dem rechten Bein, beugen Sie das linke Knie und greifen Sie den linken Knöchel. Ziehen Sie ihn sanft in Richtung Gesäß. Halten Sie die Knie zusammen.",
      quadStretchRight_name: "Quadrizeps-Dehnung (Rechts)",
      quadStretchRight_explanation: "Stehen Sie auf dem linken Bein, beugen Sie das rechte Knie und greifen Sie den rechten Knöchel. Ziehen Sie ihn sanft in Richtung Gesäß. Halten Sie die Knie zusammen.",
      wallCalfStretchLeft_name: "Waden-Dehnung an der Wand (Links)",
      wallCalfStretchLeft_explanation: "Stellen Sie sich mit dem Gesicht zur Wand. Stützen Sie sich mit den Händen an der Wand ab. Treten Sie mit dem linken Fuß zurück, halten Sie das linke Bein gerade und die Ferse auf dem Boden. Lehnen Sie sich gegen die Wand, bis Sie eine Dehnung in der linken Wade spüren.",
      wallCalfStretchRight_name: "Waden-Dehnung an der Wand (Rechts)",
      wallCalfStretchRight_explanation: "Stellen Sie sich mit dem Gesicht zur Wand. Stützen Sie sich mit den Händen an der Wand ab. Treten Sie mit dem rechten Fuß zurück, halten Sie das rechte Bein gerade und die Ferse auf dem Boden. Lehnen Sie sich gegen die Wand, bis Sie eine Dehnung in der rechten Wade spüren.",
      eccentricCalfRaiseLeft_name: "Exzentrisches Wadenheben (Links)",
      eccentricCalfRaiseLeft_explanation: "Stehen Sie auf einer Stufe auf Ihrem linken Fuß. Heben Sie sich auf den Fußballen, dann senken Sie die Ferse langsam unter das Stufenniveau.",
      eccentricCalfRaiseRight_name: "Exzentrisches Wadenheben (Rechts)",
      eccentricCalfRaiseRight_explanation: "Stehen Sie auf einer Stufe auf Ihrem rechten Fuß. Heben Sie sich auf den Fußballen, dann senken Sie die Ferse langsam unter das Stufenniveau.",
      shortFootLeft_name: "Kurzer Fuß (Links)",
      shortFootLeft_explanation: "Sitzen oder stehen Sie barfuß. Halten Sie Ihre linke Ferse und den Ballen Ihrer Zehen auf dem Boden. Ziehen Sie den Ballen Ihres linken Fußes in Richtung Ferse und wölben Sie den Mittelfuß. Halten, dann entspannen.",
      shortFootRight_name: "Kurzer Fuß (Rechts)",
      shortFootRight_explanation: "Sitzen oder stehen Sie barfuß. Halten Sie Ihre rechte Ferse und den Ballen Ihrer Zehen auf dem Boden. Ziehen Sie den Ballen Ihres rechten Fußes in Richtung Ferse und wölben Sie den Mittelfuß. Halten, dann entspannen.",
      ywRaises_name: "Y-W-Heben (Stehend)",
      ywRaises_explanation: "Aufrecht stehen. Heben Sie die Arme nach oben in eine 'Y'-Form und spannen Sie die Schultern an. Senken Sie sie ab, ziehen Sie dann die Schulterblätter zusammen und die Ellbogen nach unten in eine 'W'-Form. Wiederholen.",
      activeHang_name: "Aktives Hängen",
      activeHang_explanation: "Hängen Sie sich an eine Klimmzugstange. Spannen Sie Ihre Latissimus- und Schultermuskeln an, indem Sie die Schulterblätter nach unten und hinten ziehen und die Brust leicht anheben. Halten.",
      childPose_name: "Stellung des Kindes",
      childPose_explanation: "Knien Sie auf dem Boden, setzen Sie sich auf die Fersen und beugen Sie sich nach vorne, wobei Sie die Arme vor sich auf dem Boden ausstrecken.",
      negativePullups_name: "Negative Klimmzüge",
      negativePullups_explanation: "Springen Sie oder verwenden Sie eine Kiste, um Ihr Kinn über die Stange zu bringen. Senken Sie sich langsam und kontrolliert ab, bis Ihre Arme vollständig gestreckt sind. Wiederholen.",
      legSwingsLeft_name: "Beinschwingen (Links)",
      legSwingsLeft_explanation: "Stehen Sie aufrecht und halten Sie sich an einer Wand fest. Schwingen Sie das linke Bein vor und zurück und halten Sie die Bauchmuskeln angespannt.",
      legSwingsRight_name: "Beinschwingen (Rechts)",
      legSwingsRight_explanation: "Stehen Sie aufrecht und halten Sie sich an einer Wand fest. Schwingen Sie das rechte Bein vor und zurück und halten Sie die Bauchmuskeln angespannt.",
      jumpingJacks_name: "Hampelmann",
      jumpingJacks_explanation: "Ausgangsposition: Stehen, Beine zusammen, Arme an den Seiten. Hochspringen, Beine spreizen und die Hände über dem Kopf zusammenführen. Zurück zur Startposition.",
      armCircles_name: "Armkreisen",
      armCircles_explanation: "Stehen Sie mit den Füßen schulterbreit auseinander und strecken Sie die Arme parallel zum Boden. Machen Sie kleine kreisende Bewegungen mit beiden Armen, dann Richtung wechseln.",
      gluteBridgeDynamic_name: "Dynamische Gesäßbrücke",
      gluteBridgeDynamic_explanation: "Legen Sie sich auf den Rücken, Beine angewinkelt. Spannen Sie das Gesäß an und heben Sie die Hüfte an. Senken Sie sie wieder und wiederholen Sie die Bewegung.",
      plankToeTouches_name: "Plank Toe Touches",
      plankToeTouches_explanation: "Beginnen Sie im hohen Liegestütz. Schieben Sie Ihr Gesäß nach oben und berühren Sie mit der rechten Hand den linken Fuß. Zurück in die Planke und Seite wechseln.",
      threadNeedleLeft_name: "Nadelöhr (Links)",
      threadNeedleLeft_explanation: "Schiebe im Vierfüßlerstand deinen linken Arm unter deinen rechten, um das Schulterblatt zu öffnen.",
      threadNeedleRight_name: "Nadelöhr (Rechts)",
      threadNeedleRight_explanation: "Schiebe im Vierfüßlerstand deinen rechten Arm unter deinen linken, um das Schulterblatt zu öffnen.",
      deadBug_name: "Dead Bug",
      deadBug_explanation: "Langsam und kontrolliert! Drücke deinen unteren Rücken fest auf den Boden.",
      reverseLungeLLegLead_name: "Ausfallschritt nach hinten (L-Bein vorne)",
      reverseLungeLLegLead_explanation: "Treten Sie mit dem rechten Bein zurück. Halten Sie den Oberkörper streng vertikal.",
      reverseLungeRLegLead_name: "Ausfallschritt nach hinten (R-Bein vorne)",
      reverseLungeRLegLead_explanation: "Treten Sie mit dem linken Bein zurück. Halten Sie den Oberkörper streng vertikal.",
      standingRollDown_name: "Abrollen im Stand",
      standingRollDown_explanation: "Rollen Sie Wirbel für Wirbel nach unten zu Ihren Zehen ab, dann langsam wieder aufrollen.",
    }
  },
  es: {
    mute: 'Silenciar',
    unmute: 'Activar sonido',
    baseWorkout: 'Entrenamiento base',
    advancedWorkout: 'Entrenamiento avanzado',
    restDuration: 'Duración del descanso',
    exerciseDurationMultiplier: 'Multiplicador de duración',
    fullWorkoutRoutine: 'Rutina de entrenamiento completa',
    startWorkout: 'Empezar entrenamiento',
    startOver: 'Empezar de nuevo',
    totalTimeLeft: 'Tiempo total restante:',
    movement: 'Movimiento:',
    exerciseAnimation: 'Animación del ejercicio',
    next: 'Siguiente:',
    finalRoundComplete: '¡Última ronda completada!',
    coolDown: 'Tiempo para enfriar y estirar.',
    goBack: 'Atrás',
    skipRest: 'Saltar descanso',
    skipExercise: 'Saltar ejercicio',
    pause: 'Pausa',
    pauseRest: 'Pausa (Descanso)',
    resume: 'REANUDAR',
    paused: 'EN PAUSA',
    total: 'Total:',
    exercise: 'Ejercicio',
    of: 'de',
    rest: 'DESCANSO',
    round: 'Ronda',
    complete: 'Completado',
    workoutTitle: 'Entrenamiento',
    clickStart: 'Ajusta la configuración a continuación y presiona Empezar cuando estés listo.',
    workoutComplete: '¡Entrenamiento completado!',
    workoutCompleteMessage: '¡Buen trabajo! Has completado tu entrenamiento.',
    updateAvailable: '¡Una nueva versión está disponible!',
    applyUpdate: 'Actualizar ahora',
    installApp: 'Instalar la aplicación',
    exercises: {
      catCow_name: "Gato-Vaca",
      catCow_explanation: "Comienza a cuatro patas. Inhala mientras bajas el abdomen y miras hacia arriba (Vaca). Exhala mientras redondeas la columna y metes la barbilla (Gato).",
      birdDogLeft_name: "Pájaro-Perro (izquierda)",
      birdDogLeft_explanation: "Comienza a cuatro patas. Extiende el brazo izquierdo hacia adelante y la pierna derecha hacia atrás. Mantén.",
      birdDogRight_name: "Pájaro-Perro (derecha)",
      birdDogRight_explanation: "Comienza a cuatro patas. Extiende el brazo derecho hacia adelante y la pierna izquierda hacia atrás. Mantén.",
      pushUps_name: "Flexiones",
      pushUps_explanation: "Comienza en una plancha alta. Baja el cuerpo hasta que el pecho casi toque el suelo, manteniendo el cuerpo recto. Vuelve a subir.",
      singleLegGluteBridgeLeft_name: "Puente de glúteos a una pierna (Izquierda)",
      singleLegGluteBridgeLeft_explanation: "Acuéstate boca arriba, rodillas dobladas. Extiende la pierna derecha. Levanta las caderas usando el glúteo izquierdo hasta que el cuerpo forme una línea recta. Aprieta y luego baja.",
      singleLegGluteBridgeRight_name: "Puente de glúteos a una pierna (Derecha)",
      singleLegGluteBridgeRight_explanation: "Acuéstate boca arriba, rodillas dobladas. Extiende la pierna izquierda. Levanta las caderas usando el glúteo derecho hasta que el cuerpo forme una línea recta. Aprieta y luego baja.",
      sidePlankRight_name: "Plancha lateral (derecha)",
      sidePlankRight_explanation: "Acuéstate sobre tu lado derecho, apoya el peso en tu antebrazo derecho, levanta las caderas hasta que el cuerpo forme una línea recta.",
      sidePlankLeft_name: "Plancha lateral (izquierda)",
      sidePlankLeft_explanation: "Acuéstate sobre tu lado izquierdo, apoya el peso en tu antebrazo izquierdo, levanta las caderas hasta que el cuerpo forme una línea recta.",
      plank_name: "Plancha",
      plank_explanation: "Mantén la posición de flexión sobre los antebrazos, manteniendo una línea recta desde la cabeza hasta los talones.",
      cossackSquats_name: "Sentadillas Cosacas",
      cossackSquats_explanation: "Párate con los pies más anchos que el ancho de los hombros. Cambia tu peso hacia un lado, doblando esa rodilla mientras mantienes la otra pierna recta. Mantén el pecho erguido. Regresa al inicio y repite en el otro lado.",
      quadStretchLeft_name: "Estiramiento de cuádriceps (izquierda)",
      quadStretchLeft_explanation: "Párate sobre tu pierna derecha, dobla tu rodilla izquierda y agarra tu tobillo izquierdo. Tíralo suavemente hacia tus glúteos. Mantén las rodillas juntas.",
      quadStretchRight_name: "Estiramiento de cuádriceps (derecha)",
      quadStretchRight_explanation: "Párate sobre tu pierna izquierda, dobla tu rodilla derecha y agarra tu tobillo derecho. Tíralo suavemente hacia tus glúteos. Mantén las rodillas juntas.",
      wallCalfStretchLeft_name: "Estiramiento de gemelos en pared (izquierda)",
      wallCalfStretchLeft_explanation: "Párate frente a una pared. Apoya las manos en la pared. Da un paso atrás con el pie izquierdo, manteniendo la pierna izquierda recta y el talón en el suelo. Inclínate hacia la pared hasta que sientas un estiramiento en el gemelo izquierdo.",
      wallCalfStretchRight_name: "Estiramiento de gemelos en pared (derecha)",
      wallCalfStretchRight_explanation: "Párate frente a una pared. Apoya las manos en la pared. Da un paso atrás con el pie derecho, manteniendo la pierna derecha recta y el talón en el suelo. Inclínate hacia la pared hasta que sientas un estiramiento en el gemelo derecho.",
      eccentricCalfRaiseLeft_name: "Elevación de gemelos excéntrica (Izquierda)",
      eccentricCalfRaiseLeft_explanation: "Párate en un escalón sobre tu pie izquierdo. Sube sobre la punta del pie, luego baja lentamente el talón por debajo del nivel del escalón.",
      eccentricCalfRaiseRight_name: "Elevación de gemelos excéntrica (Derecha)",
      eccentricCalfRaiseRight_explanation: "Párate en un escalón sobre tu pie derecho. Sube sobre la punta del pie, luego baja lentamente el talón por debajo del nivel del escalón.",
      shortFootLeft_name: "Pie Corto (Izquierda)",
      shortFootLeft_explanation: "Siéntate o párate descalzo. Mantén tu talón izquierdo y la base de los dedos en el suelo. Tira del metatarso de tu pie izquierdo hacia tu talón, arqueando el mediopié. Mantén, luego relaja.",
      shortFootRight_name: "Pie Corto (Derecha)",
      shortFootRight_explanation: "Siéntate o párate descalzo. Mantén tu talón derecho y la base de los dedos en el suelo. Tira del metatarso de tu pie derecho hacia tu talón, arqueando el mediopié. Mantén, luego relaja.",
      ywRaises_name: "Elevaciones Y-W (De pie)",
      ywRaises_explanation: "Párate derecho. Levanta los brazos para formar una 'Y', apretando los hombros. Bájalos, luego junta los omóplatos tirando los codos hacia abajo para formar una 'W'. Repite.",
      activeHang_name: "Colgado Activo",
      activeHang_explanation: "Cuélgate de una barra de dominadas. Activa tus dorsales y hombros tirando de los omóplatos hacia abajo y hacia atrás, levantando ligeramente el pecho. Mantén la posición.",
      childPose_name: "Postura del niño",
      childPose_explanation: "Arrodíllate en el suelo, siéntate sobre los talones y inclínate hacia adelante, estirando los brazos frente a ti en el suelo.",
      negativePullups_name: "Dominadas Negativas",
      negativePullups_explanation: "Salta o usa un cajón para pasar la barbilla por encima de la barra. Baja lenta y controladamente hasta que tus brazos estén completamente extendidos. Repite.",
      legSwingsLeft_name: "Balanceo de pierna (Izquierda)",
      legSwingsLeft_explanation: "Párate derecho, sujétate a una pared para mantener el equilibrio. Balancea la pierna izquierda hacia adelante y hacia atrás, manteniendo el core firme.",
      legSwingsRight_name: "Balanceo de pierna (Derecha)",
      legSwingsRight_explanation: "Párate derecho, sujétate a una pared para mantener el equilibrio. Balancea la pierna derecha hacia adelante y hacia atrás, manteniendo el core firme.",
      jumpingJacks_name: "Saltos de tijera (Jumping Jacks)",
      jumpingJacks_explanation: "De pie con las piernas juntas. Salta, separando las piernas y llevando ambas manos por encima de la cabeza. Regresa a la posición inicial.",
      armCircles_name: "Círculos con los brazos",
      armCircles_explanation: "Párate con los pies separados a la anchura de los hombros y extiende los brazos. Haz pequeños movimientos circulares, y a la mitad, cambia de dirección.",
      gluteBridgeDynamic_name: "Puente de glúteos dinámico",
      gluteBridgeDynamic_explanation: "Acuéstate boca arriba, rodillas dobladas. Aprieta los glúteos y empuja las caderas hacia el techo. Baja y repite.",
      plankToeTouches_name: "Toques de pie en plancha",
      plankToeTouches_explanation: "Comienza en la posición de plancha alta. Sube las caderas y trata de tocar el pie izquierdo con la mano derecha. Vuelve a la plancha y alterna.",
      threadNeedleLeft_name: "Enhebrar la aguja (Izquierda)",
      threadNeedleLeft_explanation: "A cuatro patas, desliza el brazo izquierdo por debajo del derecho para abrir el omóplato.",
      threadNeedleRight_name: "Enhebrar la aguja (Derecha)",
      threadNeedleRight_explanation: "A cuatro patas, desliza el brazo derecho por debajo del izquierdo para abrir el omóplato.",
      deadBug_name: "Bicho muerto",
      deadBug_explanation: "¡Lento y controlado! Presiona la parte inferior de tu espalda firmemente contra el suelo.",
      reverseLungeLLegLead_name: "Zancada inversa (pierna izquierda adelantada)",
      reverseLungeLLegLead_explanation: "Da un paso atrás con la pierna derecha. Mantén el torso estrictamente vertical.",
      reverseLungeRLegLead_name: "Zancada inversa (pierna derecha adelantada)",
      reverseLungeRLegLead_explanation: "Da un paso atrás con la pierna izquierda. Mantén el torso estrictamente vertical.",
      standingRollDown_name: "Desenrollo de pie",
      standingRollDown_explanation: "Desciende vértebra por vértebra hacia tus pies, y luego sube lentamente.",
    }
  },
  uk: {
    mute: 'Вимкнути звук',
    unmute: 'Увімкнути звук',
    baseWorkout: 'Базове тренування',
    advancedWorkout: 'Просунуте тренування',
    restDuration: 'Тривалість відпочинку',
    exerciseDurationMultiplier: 'Множник тривалості',
    fullWorkoutRoutine: 'Програма тренування',
    startWorkout: 'Почати тренування',
    startOver: 'Почати спочатку',
    totalTimeLeft: 'Загальний час:',
    movement: 'Рух:',
    exerciseAnimation: 'Анімація вправи',
    next: 'Наступна:',
    finalRoundComplete: 'Останній раунд завершено!',
    coolDown: 'Час для заминки та розтяжки.',
    goBack: 'Назад',
    skipRest: 'Пропустити відпочинок',
    skipExercise: 'Пропустити вправу',
    pause: 'Пауза',
    pauseRest: 'Пауза (відпочинок)',
    resume: 'ПРОДОВЖИТИ',
    paused: 'ПАУЗА',
    total: 'Всього:',
    exercise: 'Вправа',
    of: 'з',
    rest: 'ВІДПОЧИНОК',
    round: 'Раунд',
    complete: 'Виконано',
    workoutTitle: 'Тренування',
    clickStart: 'Налаштуйте параметри нижче, а потім натисніть Старт, коли будете готові.',
    workoutComplete: 'Тренування завершено!',
    workoutCompleteMessage: 'Відмінна робота! Тренування завершено.',
    updateAvailable: 'Доступна нова версія!',
    applyUpdate: 'Оновити зараз',
    installApp: 'Встановити додаток',
    exercises: {
      catCow_name: "Кішка-Корова",
      catCow_explanation: "Почніть навкарачки. Вдихніть, прогинаючи спину і дивлячись вгору (Корова). Видихніть, округлюючи спину і притискаючи підборіддя до грудей (Кішка).",
      birdDogLeft_name: "Птах-Собака (ліва)",
      birdDogLeft_explanation: "Почніть навкарачки. Витягніть ліву руку вперед і праву ногу назад. Утримуйте.",
      birdDogRight_name: "Птах-Собака (права)",
      birdDogRight_explanation: "Почніть навкарачки. Витягніть праву руку вперед і ліву ногу назад. Утримуйте.",
      pushUps_name: "Віджимання",
      pushUps_explanation: "Почніть у високій планці. Опускайте тіло, доки груди майже не торкнуться підлоги, тримаючи тіло прямо. Поверніться у вихідне положення.",
      singleLegGluteBridgeLeft_name: "Сідничний місток на одній нозі (ліва)",
      singleLegGluteBridgeLeft_explanation: "Ляжте на спину, коліна зігнуті. Випряміть праву ногу. Піднімайте стегна за рахунок лівої сідниці, доки тіло не утворить пряму лінію. Напружте сідницю, потім опустіться.",
      singleLegGluteBridgeRight_name: "Сідничний місток на одній нозі (права)",
      singleLegGluteBridgeRight_explanation: "Ляжте на спину, коліна зігнуті. Випряміть ліву ногу. Піднімайте стегна за рахунок правої сідниці, доки тіло не утворить пряму лінію. Напружте сідницю, потім опустіться.",
      sidePlankRight_name: "Бічна планка (права)",
      sidePlankRight_explanation: "Ляжте на правий бік, спираючись на праве передпліччя, підніміть стегна, доки тіло не утворить пряму лінію.",
      sidePlankLeft_name: "Бічна планка (ліва)",
      sidePlankLeft_explanation: "Ляжте на лівий бік, спираючись на ліве передпліччя, підніміть стегна, доки тіло не утворить пряму лінію.",
      plank_name: "Планка",
      plank_explanation: "Утримуйте положення віджимання на передпліччях, зберігаючи пряму лінію від голови до п'ят.",
      cossackSquats_name: "Козацькі присідання",
      cossackSquats_explanation: "Станьте, ноги ширше плечей. Перенесіть вагу на одну сторону, зігнувши це коліно, залишаючи іншу ногу прямою. Тримайте груди прямо. Поверніться у вихідне положення і повторіть на інший бік.",
      quadStretchLeft_name: "Розтяжка квадрицепса (ліва)",
      quadStretchLeft_explanation: "Станьте на праву ногу, зігніть ліве коліно і візьміться за ліву кісточку. М'яко потягніть її до сідниць. Тримайте коліна разом.",
      quadStretchRight_name: "Розтяжка квадрицепса (права)",
      quadStretchRight_explanation: "Станьте на ліву ногу, зігніть праве коліно і візьміться за праву кісточку. М'яко потягніть її до сідниць. Тримайте коліна разом.",
      wallCalfStretchLeft_name: "Розтяжка литок біля стіни (ліва)",
      wallCalfStretchLeft_explanation: "Станьте обличчям до стіни. Зіпріться руками об стіну. Відступіть лівою ногою назад, тримаючи ліву ногу прямою, а п'яту на підлозі. Нахиліться до стіни, поки не відчуєте розтягнення в лівій литці.",
      wallCalfStretchRight_name: "Розтяжка литок біля стіни (права)",
      wallCalfStretchRight_explanation: "Станьте обличчям до стіни. Зіпріться руками об стіну. Відступіть правою ногою назад, тримаючи праву ногу прямою, а п'яту на підлозі. Нахиліться до стіни, поки не відчуєте розтягнення в правій литці.",
      eccentricCalfRaiseLeft_name: "Ексцентричне підняття на носок (ліва)",
      eccentricCalfRaiseLeft_explanation: "Станьте на сходинку на ліву ногу. Піднявшись на носок, повільно опустіть п'яту нижче рівня сходинки.",
      eccentricCalfRaiseRight_name: "Ексцентричне підняття на носок (права)",
      eccentricCalfRaiseRight_explanation: "Станьте на сходинку на праву ногу. Піднявшись на носок, повільно опустіть п'яту нижче рівня сходинки.",
      shortFootLeft_name: "Коротка стопа (ліва)",
      shortFootLeft_explanation: "Сядьте або станьте босоніж. Тримайте ліву п'яту та основу пальців ніг на підлозі. Потягніть подушечку лівої стопи до п'яти, піднімаючи звід стопи. Утримуйте, потім розслабте.",
      shortFootRight_name: "Коротка стопа (права)",
      shortFootRight_explanation: "Сядьте або станьте босоніж. Тримайте праву п'яту та основу пальців ніг на підлозі. Потягніть подушечку правої стопи до п'яти, піднімаючи звід стопи. Утримуйте, потім розслабте.",
      ywRaises_name: "Y-W підйоми (стоячи)",
      ywRaises_explanation: "Станьте прямо. Підніміть руки вгору, утворюючи форму 'Y', зводячи лопатки. Опустіть їх, потім зведіть лопатки разом, опускаючи лікті вниз, утворюючи форму 'W'. Повторіть.",
      activeHang_name: "Активний вис на турніку",
      activeHang_explanation: "Повисніть на турніку. Напружте найширші м'язи та плечі, опустивши лопатки вниз і назад, злегка піднявши груди. Утримуйте положення.",
      childPose_name: "Поза дитини",
      childPose_explanation: "Встаньте на коліна, сядьте на п'яти і нахиліться вперед, витягнувши руки перед собою на підлозі.",
      negativePullups_name: "Негативні підтягування",
      negativePullups_explanation: "Підстрибніть або використовуйте підставку, щоб підборіддя опинилося над поперечиною. Повільно і під контролем опускайтеся, поки руки повністю не випрямляться. Повторіть.",
      legSwingsLeft_name: "Махи ногою (ліва)",
      legSwingsLeft_explanation: "Станьте прямо, тримайтеся за стіну для рівноваги. Робіть махи лівою ногою вперед і назад, напружуючи м'язи кора.",
      legSwingsRight_name: "Махи ногою (права)",
      legSwingsRight_explanation: "Станьте прямо, тримайтеся за стіну для рівноваги. Робіть махи правою ногою вперед і назад, напружуючи м'язи кора.",
      jumpingJacks_name: "Джампінг Джек (Стрибки)",
      jumpingJacks_explanation: "Станьте прямо, ноги разом. Підстрибніть, розведіть ноги в сторони і плесніть в долоні над головою. Поверніться у вихідне положення.",
      armCircles_name: "Колові обертання руками",
      armCircles_explanation: "Станьте, ноги на ширині плечей, витягніть руки паралельно підлозі. Робіть невеликі колові рухи руками, потім змініть напрямок.",
      gluteBridgeDynamic_name: "Динамічний сідничний місток",
      gluteBridgeDynamic_explanation: "Ляжте на спину, зігніть коліна. Напружте сідниці та підніміть таз вгору. Потім опустіться назад і повторіть.",
      plankToeTouches_name: "Планка з торканням стопи",
      plankToeTouches_explanation: "Почніть у високій планці. Підніміть таз вгору, торкаючись правою рукою лівої стопи. Поверніться у планку і змініть сторону.",
      threadNeedleLeft_name: "Протягування нитки в голку (ліва)",
      threadNeedleLeft_explanation: "Навкарачки просуньте ліву руку під праву, щоб розкрити лопатку.",
      threadNeedleRight_name: "Протягування нитки в голку (права)",
      threadNeedleRight_explanation: "Навкарачки просуньте праву руку під ліву, щоб розкрити лопатку.",
      deadBug_name: "Мертвий жук",
      deadBug_explanation: "Повільно та контрольовано! Щільно притисніть поперек до підлоги.",
      reverseLungeLLegLead_name: "Зворотний випад (ліва нога попереду)",
      reverseLungeLLegLead_explanation: "Зробіть крок назад правою ногою. Тримайте тулуб строго вертикально.",
      reverseLungeRLegLead_name: "Зворотний випад (права нога попереду)",
      reverseLungeRLegLead_explanation: "Зробіть крок назад лівою ногою. Тримайте тулуб строго вертикально.",
      standingRollDown_name: "Розкручування стоячи",
      standingRollDown_explanation: "Нахиляйтеся вниз хребець за хребцем до пальців ніг, а потім повільно піднімайтеся.",
    }
  }
};

/** Helper function to check if a language code is one of our supported languages. */
function isSupportedLanguage(lang: string): lang is Language {
  return ['en', 'ru', 'de', 'es', 'uk'].includes(lang);
}

/** Determines the initial language based on user preference, browser settings, or a default. */
function getInitialLanguage(): Language {
  // 1. Check for a previously selected language in localStorage (user override).
  if (typeof window !== 'undefined' && window.localStorage) {
    const savedLang = localStorage.getItem(LOCAL_STORAGE_KEY_LANGUAGE);
    if (savedLang && isSupportedLanguage(savedLang)) {
      return savedLang;
    }
  }

  // 2. Detect browser language preference.
  if (typeof window !== 'undefined' && window.navigator) {
    // `navigator.languages` is an array of preferred languages, sorted by preference.
    // We iterate through it and use the first one that our app supports.
    const browserLangs = window.navigator.languages || [window.navigator.language];
    for (const lang of browserLangs) {
      const primaryLang = lang.split('-')[0]; // 'en-US' -> 'en'
      if (isSupportedLanguage(primaryLang)) {
        return primaryLang;
      }
    }
  }

  // 3. Default to English if no preference is found or supported.
  return 'en';
}

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  language = signal<Language>(getInitialLanguage());
  dictionary = computed(() => dictionaries[this.language()]);

  constructor() {
    effect(() => {
      const lang = this.language();
      if (typeof window !== 'undefined' && window.localStorage) {
        localStorage.setItem(LOCAL_STORAGE_KEY_LANGUAGE, lang);
      }
    });
  }

  setLanguage(lang: Language) {
    this.language.set(lang);
  }

  getEnglishExerciseName(key: string): string {
    return dictionaries.en.exercises[key] || key;
  }
}
